# Generated by Django 5.2.15 on 2026-06-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
