# Generated by Django 5.2.15 on 2026-06-10 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_contractor_user_maintenancejob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('bungalow', 'Bungalow'), ('other', 'Other')], default='house', max_length=20),
            preserve_default=False,
        ),
    ]
