# Generated by Django 5.2.15 on 2026-06-12 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_property_created_at_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s()-]{7,20}$')]),
        ),
    ]
